### ISSUE TITLE
Binaries are not executable

### ISSUE THREAD

**Issue by ahimmighofen** [CodeImp/arch_packages#1]
Hi,
I tried your scripts (and they are working quite nicely) and found a minor issue:
the binaries copied to /usr/bin are not marked as executable.

Have a nice Easter weekend,
André

**Comment by chris400** [comment]
chmod is set to 744, imho all things in /usr/bin should be executeable by everyone, so I'm with you, @ahimmighofen :)

**Comment by CodeImp** [comment]
Thanks!
Try new version 1.0.1.364.

**Comment by CodeImp** [comment]
close
