### ISSUE TITLE
AUR Package

### ISSUE THREAD

**Issue by saibotk** [CodeImp/arch_packages#4]
Would be cool to see this as a package in the AUR, any plans on this?

**Comment by CodeImp** [comment]
Yes. Ok. Will try to find time.
--
Wednesday, 23 January 2019, 10:34PM +03:00 from saibotk  notifications@github.com :

**Comment by CodeImp** [comment]
Is done. You can use.
Thank you for your attention to the Veeam`s product.
I will wait for feedback.

**Comment by CodeImp** [comment]
close
